### ISSUE TITLE
Make unit tests

### ISSUE THREAD

**Issue by fr05t1k** [fr05t1k/codeception-progress-reporter#1]

**Comment by klnjmm** [comment]
Hi,
Is it OK to use atoum framework for unit tests ?
I can write some of them if OK.

**Comment by fr05t1k** [comment]
Please use codeception for it. We already have this framework.

**Comment by klnjmm** [comment]
Ok I take care of it.

**Comment by fr05t1k** [comment]
@klnjmm Do you have any estimates?
