### ISSUE TITLE
Silent/Quite mode implementation

### ISSUE THREAD

**Issue by fr05t1k** [fr05t1k/codeception-progress-reporter#2]
Codeception has flags: 
--silent Only outputs suite names and final results
-q, --quiet Do not output any message

This flags should work properly.

**Comment by Rishabh04-02** [comment]
I'd like to work on the issue, but needs elaboration of the issue.
Will you please elaborate this issue?

**Comment by fr05t1k** [comment]
@Rishabh04-02 I've updated this issue.

**Comment by Rishabh04-02** [comment]
@fr05t1k Great, I'll work on it.

**Comment by Rishabh04-02** [comment]
@fr05t1k I need instructions to run it locally, I'm unable to do so.

**Comment by fr05t1k** [comment]
```
script:
  - sh ./maketests.sh
  - php vendor/bin/codecept run

**Comment by fr05t1k** [comment]
You can generate stubs by this commands and run tests

**Comment by Rishabh04-02** [comment]
@fr05t1k I've made the changes.
Now in silent mode its displaying output like this -
```
Current test: Test200Test
Success: 100 Errors: 0 Fails: 0
Current test: Test9Test
Success: 100 Errors: 0 Fails: 0


Time: 413 ms, Memory: 14.00MB
```
Is that what you require?

**Comment by fr05t1k** [comment]
I think it should look like this
![2017-10-04_19-15-57](https://user-images.githubusercontent.com/2131624/31186832-7ad3f0fa-a938-11e7-8bbb-c9d5e2c94ffb.png)

**Comment by Rishabh04-02** [comment]
Then whats the difference between `-q` and `--silent`?

**Comment by fr05t1k** [comment]
I have no idea. This is the default behavior for the default reporter on the screen above. It should be similar.
