### ISSUE TITLE
Disable when codeception is running in debug mode

### ISSUE THREAD

**Issue by Mte90** [fr05t1k/codeception-progress-reporter#21]
Right now if I am use `codecept_debug` this librar overwrite what is written with messing the output.
To solve I remove when I am doing this kind of debugging but if can do it automatically will be awesome.

**Comment by fr05t1k** [comment]
Codeception has debug mode with `-d` flag. If the flag is provided the extension is disabled.

```
codecept run unit -d
```

I hope it will help :)

**Comment by Mte90** [comment]
I always used `-vv` with codeception, if the workflow is the same I will use the other command :-D
