### ISSUE TITLE
Impossible to identify suite name

### ISSUE THREAD

**Issue by roslov** [fr05t1k/codeception-progress-reporter#8]
**Description:**
When tests are running it’s impossible to see which suite is being processed.

**Version:**
1.0.5

**Steps to reproduce:**
Start test with at least two suites.

**Actual result:**
We see current test.

**Expected result:**
We should current test and **suite name** too.

On the screenshot below it’s hard to understand where are API v1 tests, API v2 tests, functional tests or unit tests.
 
![Screenshot](http://joxi.ru/E2pGDqsByDL8mY?d=1)

**Comment by fr05t1k** [comment]
Thanks! I'll add in next version.
